### ISSUE TITLE
Load direct json data to view, no need to define model.

### ISSUE THREAD

**Issue by ngocthanhit** [rsoika/ben.js#36]
How can i load data direct direct return from ajax call to view data-ben-foreach with define the modal? 
For sample, 
  $.getJSON(
       "/backlog/rest-service/",function(data) {
         myController.model = data;
         myController.push();
       });
And i want to display data to : 
<div data-ben-foreach="myController.model">
     City=<span data-ben-model="city"></span> <br />
</div>

Can you guide me this case?

**Comment by rsoika** [comment]
The 'data-ben-foreach' directive assumes that the given object is an array. 
So if your data object contains an array of 'city' objects - e.g. 'cities', than you can push the data like this:
 
```
<div data-ben-foreach="cities">
     Name=<span data-ben-model="name"></span> 
</div
```

or if you data is an array with names than try:
```
<div data-ben-foreach=".">
     Name=<span data-ben-model="name"></span> 
</div
```

Maybe you can post an example of your data here.

**Comment by MilestoneTech** [comment]
Oh Thanks Ralph. I can loop data using data-ben-foreach. I am starting to use your lib so sure will ask you more :)

**Comment by ngocthanhit** [comment]
Oh Thanks Ralph. I can loop data using data-ben-foreach. I am starting to use your lib so sure will ask you more :)

**Comment by ngocthanhit** [comment]
@rsoika I have another question on dynamic routes, is ben.js support dynamic route like /posts/:id/:title? i was checked your sample but seem ben.js didn't support. Or will i use router.js to handle it ?

**Comment by rsoika** [comment]
No there is no support for dynamic routes. A route simply loads a new page/template.

Maybe this is an possible enhancement - if you have an idea your input is welcome. 
Maybe route.js is an external solution, so we can keep BenJS minimalistic.

**Comment by ngocthanhit** [comment]
Thanks @rsoika I will try to use route.js as external solution. i will update to you after done.
